# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-04 07:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_auto_20170904_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeQuestionTestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcase', models.FileField(upload_to=b'')),
                ('lines_per_testcase', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CodeUserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_status', models.CharField(choices=[('Accepted', 'Accepted'), ('Not Accepted', 'Not Accepted')], default='Not Accepted', max_length=15)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_output', models.FileField(upload_to=b'')),
                ('wrong_line', models.IntegerField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodeQuestion',
            fields=[
            ],
            options={
                'verbose_name': 'Coding Question',
                'proxy': True,
                'verbose_name_plural': 'Coding Questions',
            },
            bases=('quiz.question',),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.CodeQuestion'),
        ),
        migrations.AddField(
            model_name='codeuserstatus',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.CodeQuestion'),
        ),
        migrations.AddField(
            model_name='codequestiontestcase',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.CodeQuestion'),
        ),
    ]
