# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-04 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='remaining_time',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
