# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-04 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_usersubmission_remaining_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codequestiontestcase',
            old_name='testcase',
            new_name='answer_file',
        ),
        migrations.AddField(
            model_name='codequestiontestcase',
            name='lines_per_answer',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='codequestiontestcase',
            name='testcase_file',
            field=models.FileField(default=1, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codequestiontestcase',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coding.CodeQuestion'),
        ),
    ]
