# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0004_auto_20170905_1814'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodeQuestionTestCase',
            new_name='CodeQuestionExtend',
        ),
    ]
