# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0006_auto_20170906_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeTestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.CodeQuestion')),
            ],
        ),
    ]
