# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0007_codetestcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeuserstatus',
            name='remaining_time',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
