# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0008_codeuserstatus_remaining_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeuserstatus',
            name='remaining_time',
            field=models.IntegerField(blank=True),
        ),
    ]
