# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0009_auto_20170906_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeuserstatus',
            name='remaining_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
