# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-02 06:15
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FillChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FillStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qstatus', models.CharField(choices=[(b'Red', b'red'), (b'Yellow', b'yellow'), (b'Green', b'green')], default=b'red', max_length=6)),
                ('answer', models.CharField(blank=True, max_length=200)),
                ('preResult', models.IntegerField(default=-1)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MultiChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('answer', models.CharField(choices=[(b'Yes', b'Yes'), (b'No', b'No')], default=b'No', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MultiStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qstatus', models.CharField(choices=[(b'Red', b'red'), (b'Yellow', b'yellow'), (b'Green', b'green')], default=b'red', max_length=6)),
                ('selected', models.IntegerField(default=-1)),
                ('preResult', models.IntegerField(default=-1)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('code', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=b'')),
                ('mark', models.IntegerField(default=1)),
                ('type', models.CharField(choices=[(b'mcq', b'mcq'), (b'fill', b'fill')], default=b'mcq', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='FillQuestion',
            fields=[
            ],
            options={
                'verbose_name': 'Fill Up',
                'proxy': True,
                'verbose_name_plural': 'Fill Ups',
            },
            bases=('quiz.question',),
        ),
        migrations.CreateModel(
            name='MultiQuestion',
            fields=[
            ],
            options={
                'verbose_name': 'Multiple Choice Questions',
                'proxy': True,
                'verbose_name_plural': 'Multiple Choice Questions',
            },
            bases=('quiz.question',),
        ),
        migrations.AddField(
            model_name='multistatus',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.MultiQuestion'),
        ),
        migrations.AddField(
            model_name='multichoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.MultiQuestion'),
        ),
        migrations.AddField(
            model_name='fillstatus',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.FillQuestion'),
        ),
        migrations.AddField(
            model_name='fillchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.FillQuestion'),
        ),
    ]
