# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='code_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
