# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20170904_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'images'),
        ),
    ]
