# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-01 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20170830_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillstatus',
            name='preResult',
            field=models.BooleanField(default=False),
        ),
    ]
