# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20161211_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
