# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20161211_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ph_no',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
