# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20170103_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='answer',
            field=models.CharField(choices=[(b'Yes', b'Yes'), (b'No', b'No')], default=b'No', max_length=3),
        ),
    ]
