# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 13:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('quiz', '0013_auto_20170106_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Qstatus', models.CharField(choices=[(b'Red', b'Red'), (b'Yellow', b'Yellow'), (b'Green', b'Green')], default=b'Red', max_length=6)),
                ('selected', models.IntegerField(default=-1)),
            ],
        ),
    ]
