# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'status'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='code_text',
        ),
        migrations.AddField(
            model_name='status',
            name='question',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Question'),
        ),
    ]
