# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20170106_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Question'),
        ),
    ]
