# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 14:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20170106_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='id',
            field=models.IntegerField(default=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
