# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='question_ptr',
        ),
        migrations.RemoveField(
            model_name='status',
            name='user',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
