# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 11:58
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('quiz', '0028_auto_20170107_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Qstatus', models.CharField(choices=[(b'Red', b'Red'), (b'Yellow', b'Yellow'), (b'Green', b'Green')], default=b'Red', max_length=6)),
                ('selected', models.IntegerField(default=-1)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
