# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('login', '0003_auto_20170106_1312'),
        ('quiz', '0029_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
