# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 12:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0031_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='User',
        ),
        migrations.AddField(
            model_name='status',
            name='User',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
