# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_remove_status_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.Question'),
        ),
    ]
