# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0036_remove_status_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='User',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default=b'asd', max_length=200),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
