# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 04:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0037_auto_20170108_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.Question')),
                ('Qstatus', models.CharField(choices=[(b'Red', b'Red'), (b'Yellow', b'Yellow'), (b'Green', b'Green')], default=b'Red', max_length=6)),
                ('selected', models.IntegerField(default=-1)),
                ('User', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            bases=('quiz.question',),
        ),
    ]
