# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0042_auto_20170113_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={},
        ),
        migrations.AlterField(
            model_name='status',
            name='Qstatus',
            field=models.CharField(choices=[(b'Red', b'red'), (b'Yellow', b'yellow'), (b'Green', b'green')], default=b'red', max_length=6),
        ),
    ]
