# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0043_auto_20170220_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='code',
            field=models.TextField(null=True),
        ),
    ]
