# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-07 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='college_name',
            field=models.CharField(default='asd', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ph_no',
            field=models.CharField(default=8969, max_length=30),
            preserve_default=False,
        ),
    ]
