# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170105_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ph_no',
            field=models.IntegerField(null=True),
        ),
    ]
