# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170106_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rmin',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rsec',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
