# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-11 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url_namespace', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'card',
                'verbose_name_plural': 'cards',
            },
        ),
        migrations.CreateModel(
            name='nav_drop_down',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url_namespace', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'navdropdown',
                'verbose_name_plural': 'navdropdown',
            },
        ),
    ]
