# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-12 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nav_drop_down',
            options={'verbose_name': 'Nav Dropdown', 'verbose_name_plural': 'Nav Dropdown'},
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nav_drop_down',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
